server:
  port: 8088

wx:
  # 服务区回调需要
  token: 222

  # 用户信息
  user:
    appid: xxx
    secret: xxx
    grant_type: client_credential


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dingyuehao?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xxx

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

image:
  path: "/Users/liuzhuohao/Documents/javaProject/dingyuehao/image/"